//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.20.0
//     from Assets/Scripts/CameraControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/CameraControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CameraControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @CameraControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""CameraControls"",
    ""maps"": [
        {
            ""name"": ""PerspChange"",
            ""id"": ""87446c1a-7710-4226-b824-6f90c4359639"",
            ""actions"": [
                {
                    ""name"": ""Perspchange"",
                    ""type"": ""Button"",
                    ""id"": ""e3620e28-48db-4aca-af0c-92655f609e74"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false,
                    ""priority"": 0
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8e52d9ed-a5bd-45c7-b654-8c894040f438"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Perspchange"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CamLook3D"",
            ""id"": ""500c82d2-faad-46dd-a142-f14690c87d0d"",
            ""actions"": [
                {
                    ""name"": ""CamMouse"",
                    ""type"": ""Value"",
                    ""id"": ""5e063f19-f770-432f-ab56-d91346f1f848"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true,
                    ""priority"": 0
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""670a91da-0611-42e5-9714-85fd1f1dcd7d"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CamMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PerspChange
        m_PerspChange = asset.FindActionMap("PerspChange", throwIfNotFound: true);
        m_PerspChange_Perspchange = m_PerspChange.FindAction("Perspchange", throwIfNotFound: true);
        // CamLook3D
        m_CamLook3D = asset.FindActionMap("CamLook3D", throwIfNotFound: true);
        m_CamLook3D_CamMouse = m_CamLook3D.FindAction("CamMouse", throwIfNotFound: true);
    }

    ~@CameraControls()
    {
        UnityEngine.Debug.Assert(!m_PerspChange.enabled, "This will cause a leak and performance issues, CameraControls.PerspChange.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CamLook3D.enabled, "This will cause a leak and performance issues, CameraControls.CamLook3D.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PerspChange
    private readonly InputActionMap m_PerspChange;
    private List<IPerspChangeActions> m_PerspChangeActionsCallbackInterfaces = new List<IPerspChangeActions>();
    private readonly InputAction m_PerspChange_Perspchange;
    /// <summary>
    /// Provides access to input actions defined in input action map "PerspChange".
    /// </summary>
    public struct PerspChangeActions
    {
        private @CameraControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PerspChangeActions(@CameraControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PerspChange/Perspchange".
        /// </summary>
        public InputAction @Perspchange => m_Wrapper.m_PerspChange_Perspchange;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PerspChange; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PerspChangeActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PerspChangeActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PerspChangeActions" />
        public void AddCallbacks(IPerspChangeActions instance)
        {
            if (instance == null || m_Wrapper.m_PerspChangeActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PerspChangeActionsCallbackInterfaces.Add(instance);
            @Perspchange.started += instance.OnPerspchange;
            @Perspchange.performed += instance.OnPerspchange;
            @Perspchange.canceled += instance.OnPerspchange;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PerspChangeActions" />
        private void UnregisterCallbacks(IPerspChangeActions instance)
        {
            @Perspchange.started -= instance.OnPerspchange;
            @Perspchange.performed -= instance.OnPerspchange;
            @Perspchange.canceled -= instance.OnPerspchange;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PerspChangeActions.UnregisterCallbacks(IPerspChangeActions)" />.
        /// </summary>
        /// <seealso cref="PerspChangeActions.UnregisterCallbacks(IPerspChangeActions)" />
        public void RemoveCallbacks(IPerspChangeActions instance)
        {
            if (m_Wrapper.m_PerspChangeActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PerspChangeActions.AddCallbacks(IPerspChangeActions)" />
        /// <seealso cref="PerspChangeActions.RemoveCallbacks(IPerspChangeActions)" />
        /// <seealso cref="PerspChangeActions.UnregisterCallbacks(IPerspChangeActions)" />
        public void SetCallbacks(IPerspChangeActions instance)
        {
            foreach (var item in m_Wrapper.m_PerspChangeActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PerspChangeActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PerspChangeActions" /> instance referencing this action map.
    /// </summary>
    public PerspChangeActions @PerspChange => new PerspChangeActions(this);

    // CamLook3D
    private readonly InputActionMap m_CamLook3D;
    private List<ICamLook3DActions> m_CamLook3DActionsCallbackInterfaces = new List<ICamLook3DActions>();
    private readonly InputAction m_CamLook3D_CamMouse;
    /// <summary>
    /// Provides access to input actions defined in input action map "CamLook3D".
    /// </summary>
    public struct CamLook3DActions
    {
        private @CameraControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CamLook3DActions(@CameraControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CamLook3D/CamMouse".
        /// </summary>
        public InputAction @CamMouse => m_Wrapper.m_CamLook3D_CamMouse;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CamLook3D; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CamLook3DActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CamLook3DActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CamLook3DActions" />
        public void AddCallbacks(ICamLook3DActions instance)
        {
            if (instance == null || m_Wrapper.m_CamLook3DActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CamLook3DActionsCallbackInterfaces.Add(instance);
            @CamMouse.started += instance.OnCamMouse;
            @CamMouse.performed += instance.OnCamMouse;
            @CamMouse.canceled += instance.OnCamMouse;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CamLook3DActions" />
        private void UnregisterCallbacks(ICamLook3DActions instance)
        {
            @CamMouse.started -= instance.OnCamMouse;
            @CamMouse.performed -= instance.OnCamMouse;
            @CamMouse.canceled -= instance.OnCamMouse;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CamLook3DActions.UnregisterCallbacks(ICamLook3DActions)" />.
        /// </summary>
        /// <seealso cref="CamLook3DActions.UnregisterCallbacks(ICamLook3DActions)" />
        public void RemoveCallbacks(ICamLook3DActions instance)
        {
            if (m_Wrapper.m_CamLook3DActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CamLook3DActions.AddCallbacks(ICamLook3DActions)" />
        /// <seealso cref="CamLook3DActions.RemoveCallbacks(ICamLook3DActions)" />
        /// <seealso cref="CamLook3DActions.UnregisterCallbacks(ICamLook3DActions)" />
        public void SetCallbacks(ICamLook3DActions instance)
        {
            foreach (var item in m_Wrapper.m_CamLook3DActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CamLook3DActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CamLook3DActions" /> instance referencing this action map.
    /// </summary>
    public CamLook3DActions @CamLook3D => new CamLook3DActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PerspChange" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PerspChangeActions.AddCallbacks(IPerspChangeActions)" />
    /// <seealso cref="PerspChangeActions.RemoveCallbacks(IPerspChangeActions)" />
    public interface IPerspChangeActions
    {
        /// <summary>
        /// Method invoked when associated input action "Perspchange" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPerspchange(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CamLook3D" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CamLook3DActions.AddCallbacks(ICamLook3DActions)" />
    /// <seealso cref="CamLook3DActions.RemoveCallbacks(ICamLook3DActions)" />
    public interface ICamLook3DActions
    {
        /// <summary>
        /// Method invoked when associated input action "CamMouse" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnCamMouse(InputAction.CallbackContext context);
    }
}
